repos:
  # Black: Code Formatter
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black

  # Flake8: Code Linter
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=90