services:
  api:
    build:
      .
    ports:
      - "8000:8000"
    develop:
      watch:
        - path: ./requirements.txt
          target: /app
          action: rebuild
        - path: ./solver
          target: /app/solver
          action: sync